# Use powerline
USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

# Kitty terminal aliases to make life easier.
# icat is used to display images inside the kitten terminal.
alias icat="kitty +kitten icat"

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Spotify fetch tool environment variables
--REDACTED--
